### ISSUE TITLE
automate Bug 1330515 - Traceback on the terminal when used CTRL+C to kill the subscription-manager-gui application

### ISSUE THREAD

**Issue by jstavel** [RedHatQE/rhsm-qe#604]
``` gherkin
Given I have openned a terminal
When I launch subscription-manager-gui from the terminal
    and I press CTRL+C on the terminal
Then no traceback should be printed in the terminal 
    and no traceback should be printed in a log file.
```

# Traceback (most recent call last):
  File "/usr/share/rhsm/subscription_manager/gui/managergui.py", line 275, in _on_cert_check_timer
    def _on_cert_check_timer(self):
KeyboardInterrupt

**Comment by jstavel** [comment]
https://trello.com/c/ZK6rr6xh

**Comment by jstavel** [comment]
Given I have openned a terminal
When I launch subscription-manager-gui from the terminal
    and I press CTRL+C on the terminal
Then no traceback should be printed in the terminal 
    and no traceback should be printed in a log file.


# Traceback (most recent call last):
  File "/usr/share/rhsm/subscription_manager/gui/managergui.py", line 275, in _on_cert_check_timer
    def _on_cert_check_timer(self):
KeyboardInterrupt

**Comment by jstavel** [comment]
Done.
